/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arg.edu.iua.presentacion;

import arg.edu.iua.ModeloDAO.exceptions.PersistenceException;
import arg.edu.iua.modelo.Usuario;
import arg.edu.iua.negocio.implement.NegocioImpl;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
    
/**
 *
 * @author Octavio
 */
public class Aqcontacos extends javax.swing.JFrame {
    Usuario u=new Usuario();
    /**
     * Creates new form Aqcontacos
     */
    public Aqcontacos() {
        initComponents();
    }

    Aqcontacos(Usuario u) {
     this.u=u;
     initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(530, 240));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        jLabel3.setText("Seguir/Dejar de seguir usuario");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 10, 320, 40);

        jLabel4.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        jLabel4.setText("Username:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 90, 130, 30);

        jTextField1.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(200, 90, 200, 30);

        jButton1.setBackground(new java.awt.Color(135, 211, 124));
        jButton1.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        jButton1.setText("Seguir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 170, 90, 30);

        jButton2.setBackground(new java.awt.Color(214, 69, 65));
        jButton2.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        jButton2.setText("Dejar de Seguir");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 170, 150, 29);

        jButton3.setFont(new java.awt.Font("Segoe Script", 3, 12)); // NOI18N
        jButton3.setText("Volver atras");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(350, 170, 120, 29);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arg/edu/iua/presentacion/utilResources/dsadsasddsa.jpg"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 510, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
      Contactos cf=new Contactos(u);
      cf.setVisible(true);
      cf.pack();
      cf.setLocationRelativeTo(null);
      cf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      this.dispose();  
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
            String uname=jTextField1.getText();
            try {
            NegocioImpl ni= new NegocioImpl();
            boolean b=ni.seguirU(u, uname);
            if(b==true){
                JOptionPane.showMessageDialog(this,"Has comenzado a seguir a "+uname);
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Usted ya sigue a "+ uname);
        } catch (PersistenceException ex) {
          JOptionPane.showMessageDialog(this,ex.getMessage());  
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String uname=jTextField1.getText();
        try {
            NegocioImpl ni= new NegocioImpl();
            boolean b=ni.dejarDeSeguirU(u, uname);
            if(b=true){
                JOptionPane.showMessageDialog(this,"Has dejado de seguir a "+uname);
            }
        } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this,"Usted no sigue a "+ uname);
        } catch (PersistenceException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aqcontacos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aqcontacos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aqcontacos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aqcontacos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aqcontacos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
