/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arg.edu.iua.presentacion;

import arg.edu.iua.modelo.Usuario;
import arg.edu.iua.modelo.exception.NoAgeException;
import arg.edu.iua.modelo.exception.NoDataFoundException;
import arg.edu.iua.negocio.exceptions.NoPasswordMatchException;
import arg.edu.iua.negocio.exceptions.ServicesException;
import arg.edu.iua.negocio.implement.NegocioImpl;
import java.awt.Frame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Octavio
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_UN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NombreFieldT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField_PS = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_AP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField_CPS = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        RegisterJb = new javax.swing.JButton();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        minJLB = new javax.swing.JLabel();
        closeJLB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(510, 520));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Username:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 200, 100, 22);

        jTextField_UN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UNActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_UN);
        jTextField_UN.setBounds(210, 200, 170, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 100, 90, 22);
        getContentPane().add(NombreFieldT);
        NombreFieldT.setBounds(210, 110, 170, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Contraseña:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 250, 110, 22);
        getContentPane().add(jPasswordField_PS);
        jPasswordField_PS.setBounds(210, 250, 170, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Apellido:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 150, 80, 22);
        getContentPane().add(jTextField_AP);
        jTextField_AP.setBounds(210, 150, 170, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Repetir Contraseña:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 300, 170, 22);
        getContentPane().add(jPasswordField_CPS);
        jPasswordField_CPS.setBounds(210, 300, 170, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Fecha de nacimiento:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 350, 180, 22);

        jButton2.setText("Cancelar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(339, 447, 75, 23);

        RegisterJb.setText("Registrarse");
        RegisterJb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterJbMouseClicked(evt);
            }
        });
        RegisterJb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterJbActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterJb);
        RegisterJb.setBounds(102, 447, 87, 23);
        getContentPane().add(dateChooserCombo2);
        dateChooserCombo2.setBounds(204, 352, 176, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("E-mail:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 390, 180, 22);

        jTextField1.setText("example@exmpl.com");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(204, 394, 176, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formulario de Registro");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 242, 29);

        minJLB.setFont(new java.awt.Font("Tahoma", 0, 65)); // NOI18N
        minJLB.setText("-");
        minJLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minJLBMouseClicked(evt);
            }
        });
        getContentPane().add(minJLB);
        minJLB.setBounds(400, 0, 24, 55);

        closeJLB.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        closeJLB.setText("X");
        getContentPane().add(closeJLB);
        closeJLB.setBounds(460, 0, 21, 55);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arg/edu/iua/presentacion/utilResources/dsadsasddsa.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-6, 0, 510, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_UNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UNActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Login lgf= new Login();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void RegisterJbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterJbMouseClicked
        System.exit(0);
    }//GEN-LAST:event_RegisterJbMouseClicked

    private void RegisterJbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterJbActionPerformed
       Usuario u=new Usuario(jTextField_UN.getText(), String.valueOf(jPasswordField_PS.getPassword()), NombreFieldT.getText(), jTextField_AP.getText(),dateChooserCombo2.getSelectedDate().getTime(), jTextField1.getText());
      
       boolean b=false;
        try {
             String cpass=String.valueOf(jPasswordField_CPS.getPassword());
             SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
            String fnac= dateformat.format(dateChooserCombo2.getSelectedDate().getTime());
            
            
            NegocioImpl ni=new NegocioImpl();
            b=ni.registrarUsuario(u, cpass,fnac);
        } catch (ServicesException ex) {
            String cadenaDondeBuscar = ex.getMessage();
            String loQueQuieroBuscar = "Username_UNIQUE";
         String[] palabras = loQueQuieroBuscar.split("\\s+");
            for (String palabra : palabras) {
            if (cadenaDondeBuscar.contains(palabra)) {
                JOptionPane.showMessageDialog(this,"El username "+u.getUsername()+" no esta diponible! ");
                }
            else{
                loQueQuieroBuscar="Email_UNIQUE";
                palabras=loQueQuieroBuscar.split("\\s+");
                if (cadenaDondeBuscar.contains(palabra)) {
                JOptionPane.showMessageDialog(this,"El email "+u.getEmail()+" no esta diponible! ");
                }
            }
        //aquí tu lógica en caso que se haya encontrado...
    }
        } catch (NoDataFoundException ex) {
            JOptionPane.showMessageDialog(this,"El campo "+ex.getMessage()+" es obligatorio! ");

        } catch (NoPasswordMatchException ex) {
           JOptionPane.showMessageDialog(this,"Las contraseñas no coinciden");
        } catch (NoAgeException ex) {
          
        }
        if(b==true){
         JOptionPane.showMessageDialog(this, "El usuario "+u.getUsername()+" se registro con exito!");
            Login lgf= new Login();
            lgf.setVisible(true);
            lgf.pack();
            lgf.setLocationRelativeTo(null);
            lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
        
    }//GEN-LAST:event_RegisterJbActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void minJLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minJLBMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minJLBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NombreFieldT;
    private javax.swing.JButton RegisterJb;
    private javax.swing.JLabel closeJLB;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField_CPS;
    private javax.swing.JPasswordField jPasswordField_PS;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_AP;
    private javax.swing.JTextField jTextField_UN;
    private javax.swing.JLabel minJLB;
    // End of variables declaration//GEN-END:variables
}
